#!/bin/sh



set -e 


case $1 in
	configure)
        	echo "postinst called with argument \`$1'" >&2
                exit 0
	;;

        abort-upgrade|abort-remove|abort-deconfigure)
                echo "postinst called with argument \`$1'" >&2
                exit 1
        ;;

        *)
                echo "postinst called with unknown argument \`$1'" >&2
                exit 1
        ;;
esac


